---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: interview-assignment
  name: interview-assignment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: interview-assignment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: interview-assignment
    spec:
      containers:
      - image: localhost:5000/interview-assignment 
        imagePullPolicy: IfNotPresent
        name: interview-assignment
        ports:
        - containerPort: 8090
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1 
kind: Service
metadata:
  labels:
    run: interview-assignment
  name: interview-assignment
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8090
  selector:
    run: interview-assignment
  sessionAffinity: None
  type: ClusterIP
